<div class="page-footer-item">
    <div class="footer-content">
        <div class="footer-blocks">
            <div class="logo-footer">
                <img class="image" src="<?= $block->getViewFileUrl('images/logo.png'); ?>" />
                <div class="footer-content-child">
                    <p>
                        <a href="#" target="_blank" rel="noopener noreferrer">Se kontrolrapport</a>
                    </p>
                    <p>Fredtoftevej 2, 2980
                        <br>
                        Kokkedal, Denmark
                        <br>
                        CVR-nr: 27490441
                    </p>
                    <p>+45 60 66 12 14
                        <br>
                        info@finewines.dk
                    </p>
                </div>
            </div>

            <div class="footer-link">
                <h2>Land</h2>
                <ul class="link-list">
                    <li><a href="#">Australien</a></li>
                    <li><a href="#">Frankrig</a></li>
                    <li><a href="#">Italien</a></li>
                    <li><a href="#">New Zealand</a></li>
                    <li><a href="#">Portugal</a></li>
                    <li><a href="#">Spanien</a></li>
                    <li><a href="#">Tyskland</a></li>
                    <li><a href="#">USA</a></li>
                    <li><a href="#">Østrig</a></li>
                </ul>
            </div>

            <div class="footer-link">
                <h2>Populære regioner</h2>
                <ul class="link-list">
                    <li><a href="#">Bourgogne</a></li>
                    <li><a href="#">Bordeaux</a></li>
                    <li><a href="#">Champagne</a></li>
                    <li><a href="#">Loire</a></li>
                    <li><a href="#">Napa Valley</a></li>
                    <li><a href="#">Oregon</a></li>
                    <li><a href="#">Rhône</a></li>
                    <li><a href="#">Ribera del Duero</a></li>
                </ul>
            </div>

            <div class="footer-link">
                <h2>Populære producenter</h2>
                <ul class="link-list">
                    <li><a href="#">Arterberry Maresh</a></li>
                    <li><a href="#">Belle Glos</a></li>
                    <li><a href="#">Domaine Serene</a></li>
                    <li><a href="#">Dominio de Pingus</a></li>
                    <li><a href="#">Domaine Pierre Gelin</a></li>
                    <li><a href="#">Dominique Cornin</a></li>
                    <li><a href="#">DuMOL</a></li>
                </ul>
            </div>

            <div class="footer-link">
                <h2>Vintype</h2>
                <ul class="link-list">
                    <li><a href="#">Hvidvin</a></li>
                    <li><a href="#">Rødvin</a></li>
                    <li><a href="#">Bobler</a></li>
                    <li><a href="#">Rosé</a></li>
                    <li><a href="#">Søde vine</a></li>
                    <li><a href="#">Spiritus</a></li>
                </ul>
            </div>

            <div class="footer-link">
                <h2>Diverse</h2>
                <ul class="link-list">
                    <li><a href="#">Tilbud</a></li>
                    <li><a href="#">Restsalg</a></li>
                    <li><a href="#">Smagekasser</a></li>
                    <li><a href="#">Seneste vine</a></li>
                    <li><a href="#">SOm FineWinesmagninger</a></li>
                    <li><a href="#">Presse</a></li>
                </ul>
            </div>

            <div class="footer-link">
                <h2>Land</h2>
                <ul class="link-list">
                    <li><a href="#">Australien</a></li>
                    <li><a href="#">Frankrig</a></li>
                    <li><a href="#">SmageItalienkasser</a></li>
                    <li><a href="#">New Zealand</a></li>
                    <li><a href="#">Portugal</a></li>
                    <li><a href="#">Spanien</a></li>
                    <li><a href="#">Tyskland</a></li>
                    <li><a href="#">USA</a></li>
                    <li><a href="#">Østrig</a></li>
                </ul>
            </div>

            <div class="footer-link">
                <h2>Kundeservice</h2>
                <ul class="link-list">
                    <li><a href="#">Kontakt</a></li>
                    <li><a href="#">Betingelser</a></li>
                    <li><a href="#">Levering</a></li>
                    <li><a href="#">Refundering</a></li>
                </ul>
            </div>
            
        </div>
    </div>
</div>