<div class="content-box-2-bg1">
    <div class="colum-line1">
        <div class="img-box">
            <img class="image" src="<?= $block->getViewFileUrl('images/content-box-2/img-bg-row1.webp'); ?>" />
        </div>
        <div class="content">
            <div class="content-item">
                <img src="<?= $block->getViewFileUrl('images/content-box-2/img-text-row1.webp'); ?>" />
                <h2>Bag om FineWines</h2>
                <p>“Vin skal sprede glæde. Og jo bedre vinen er, jo større glæde spreder den.“ - Per Østergaard</p>
                <a href="#">Læs mere</a>
            </div>
        </div>
    </div>
</div>

<div class="content-box-2-bg2">
    <div class="colum-line2">
        <div class="content">
            <div class="content-item">
                <img src="<?= $block->getViewFileUrl('images/content-box-2/img-text-row2.webp'); ?>" />
                <h2>Nylige begivenheder</h2>
                <p>Gå på opdagelse i vores billedegalleri og få et indblik i vores seneste arrangementer.</p>
                <a href="#">Læs mere</a>
            </div>
        </div>
        <div class="img-box">
            <img class="image" src="<?= $block->getViewFileUrl('images/content-box-2/img-bg-row2.webp'); ?>" />
        </div>
    </div>
</div>




