<div class="content-box-bg1">
    <div class="colum-line1">
        <div class="img-box">
            <img class="image" src="<?= $block->getViewFileUrl('images/content-images/banner1.webp'); ?>" />
        </div>
        <div class="content">
            <div class="content-item">
                <img src="<?= $block->getViewFileUrl('images/content-images/banner1-right.png'); ?>" />
                <h2>Smagekasser</h2>
                <p>Se vores nøje udvalgte smagekasser, og find din næste favorit lige her</p>
                <a href="#">Se udvalg her</a>
            </div>
        </div>
    </div>
</div>

<div class="content-box-bg2">
    <div class="colum-line2">
        <div class="content">
            <div class="content-item">
                <img src="<?= $block->getViewFileUrl('images/content-images/banner2-left.webp'); ?>" />
                <h4>MÅNEDENS VIN</h4>
                <h2>Bois-Moi Chardonnay 2020</h2>
                <p>Bois-Moi betyder slet og ret ”drik mig”, hvilket flasken ikke skal sige to gange, for det er en yderst indbydende sag, som Ken Pahlow har skruet sammen her. Ingen kanter, panderynker eller andet halløj – bare uforskammet let at nyde og så til en rigtig fornuftig pris.</p>
                <a href="#">Køb her</a>
            </div>
        </div>
        <div class="img-box">
            <img class="image" src="<?= $block->getViewFileUrl('images/content-images/banner2.webp'); ?>" />
        </div>
    </div>
</div>




